### ISSUE TITLE
read_gt3x null activity?

### ISSUE THREAD

**Issue by edmundseto** [paulhibbing/AGread#35]
Thanks for developing this package. I'm a new user. 

When I call read_gt3x on an Actigraph wGT3X-BT raw gt3x file, the result contains useful metadata, parameters, battery, capsense info.  But, the activity in the result is null.  Is this expected?

The gt3x file seems OK, as I can export it to csv in Actilife, and obtain the time-series of activity that way.

Best,

Edmund

**Comment by paulhibbing** [comment]
Hi Edmund,

Thanks for reaching out. I'm happy to try diagnosing what's going on. It's been awhile since I wrote the current version of the code, but here are a few clarifying questions based on what I remember:

* Do you get any errors or warnings? 
* Does your output include a `RAW` element, or is that what you're saying is `NULL`? *(Most packet types get saved under their original names [PARAMETERS, CAPSENSE, etc.], but I think acceleration data get saved as RAW in most or all cases -- If you see that in your output, it should match what you get out of ActiLife)*
* Was your data collected through CentrePoint? *(I don't think that's applicable for wGT3X-BT, but if it is, that's a very likely culprit -- my current code often generalizes poorly to output from CentrePoint)*
* Is the output from ActiLife all 0's? *(If there's no acceleration data in the file, AGread might return `NULL`, whereas ActiLife might fill in 0's)*
* Is there a chance the data were collected using a hardware/firmware scheme that is not yet supported (see #10 and #19)? *(This might be hard to tell, which is fine -- basically there are some monitors that collect data in a different way than I currently support, which could be the issue)*

If those questions don't help us solve the issue, I can try to take a more careful look. But I will probably need you to provide a sample file if we go that route, and I know that can be an issue with research data. Hopefully it won't be necessary. Just let me know!

**Comment by edmundseto** [comment]
Hi Paul,

Your response was helpful.  I think it's related to issue #19.  

- I turned on verbose=T, and yes there were warnings/errors (in bold below):

---
Processing file.gt3x 

  Parsing info.txt  ............. COMPLETE

  Will parse the following packet types, if available:
    METADATA, PARAMETERS, SENSOR_SCHEMA, BATTERY 
    EVENT, TAG, ACTIVITY, HEART_RATE_BPM 
    HEART_RATE_ANT, HEART_RATE_BLE, LUX, CAPSENSE 
    EPOCH, EPOCH2, EPOCH3, EPOCH4 
    ACTIVITY2, SENSOR_DATA 

  Reading log.bin  ............. COMPLETE
  Getting record headers  ............... COMPLETE
  Parsing PARAMETERS packet(s)   ............. COMPLETE                      
  Parsing EVENT packet(s)   ............. COMPLETE                      
  Parsing METADATA packet(s)   ............. COMPLETE                      
  Parsing BATTERY packet(s)   ............. COMPLETE                      
  **Parsing ACTIVITY packet(s)No method exists yet for parsing ACTIVITY packets -- returning NULL.
  Parsing LUX packet(s)No method exists yet for parsing LUX packets -- returning NULL.**
  Parsing CAPSENSE packet(s)   ............. COMPLETE    

---

 - I don't see a "RAW" element.  I get a result list with METADATA, BATTERY, ACTIVITY(this is null), LUX (this is also null), CAPSENSE, PARAMETERS, and EVENT.
 - I don't think this went through Centrepoint.  I believe the study coordinator downloaded this file directly from a participant's device and provided to me.
 - Looking at the code in issue #19, I also tried running the file through the read.gt3x package. Following the vignette for that package, I was able to see the X,Y,Z data and plot a subset of the data. The accelerometry seems to exist, and is non-zero.
 - If it helps, read.gt3x reported that my devices are running firmware v1.9.2.  I did read at the bottom of issue #19 that there's a way, using parser = "dev" in AGread to parse the ACTIVITY packets that apparently my Actigraphs are saving in the gt3x files.  I'll try that soon.  But, in the meantime, the read.gt3x package seems to be a good complement to AGread for working with the files.  So if you want to close this issue, that'd be OK for me.

Thanks again,
Edmund

**Comment by paulhibbing** [comment]
Ah, I think this may be a version issue. I have made updates on GitHub that are not yet available on CRAN. I always forget about that (not the first time).

Can you try running remotes::install_github(“paulhibbing/AGread”) ? After the installation completes, you may want to restart your session before trying your file again. 

Hope that does the trick!

**Comment by paulhibbing** [comment]
Hi @edmundseto, just checking back to see if the above suggestion helped. I will probably close this issue in a week or so if there's no further discussion.
